cronjob-unauthorized-file="""
An unknown cron job file is installed by this package. Please contact the
security team to get it allowed.
"""

cronjob-changed-file="""
A cron job or cron job related file installed by this package changed in
content. Please contact the security team to get this allowed.
"""

cronjob-ghost-file="""
A cron job path has been marked as %ghost file by this package. This is not
allowed as it is impossible to review.
"""
