dbus-unauthorized-service="""
The package installs an unknown DBUS system service file. Please contact the
security team to get it allowed.
"""

dbus-ghost-service="""
This package installs a DBUS system service marked as %ghost. This is not
allowed, since it is impossible to review.
"""
