polkit-unauthorized-rules="""
A polkit rules file installed by this package is not allowed in the
polkit-whitelisting package. Please contact the security team.
"""


polkit-changed-rules="""
A polkit rules file installed by this package changed in content. Please
contact the security team.
"""


polkit-ghost-file="""
This package installs a polkit rule or policy as %ghost file. This is not
allowed as it is impossible to review.
"""
