permissions-unauthorized-file="""
An unknown file is packaged with sensitive permissions. Please contact the
security team to request review of the package by the security team.
"""



permissions-symlink="""
A symlink is packaged at a path where a file with sensitive permissions is
expected. Please contact the security team to remove the entry.
"""


permissions-dir-without-slash="""
The entry in the permissions file refers to a directory. Please contact the
security team to append a slash to the entry in order to avoid security
problems.
"""


permissions-file-as-dir="""
The entry in the permissions file refers to a directory but the package
actually contains a file. Please contact the security team to remove the slash.
"""


permissions-incorrect="""
Please use the %attr macro to set the correct permissions.
"""


permissions-incorrect-owner="""
Please use the %attr macro to set the correct ownership.
"""


permissions-file-setuid-bit="""
The file has a setuid or setgid bit set. Please contact the security team to
have it allowed.
"""


permissions-directory-setuid-bit="""
The directory has a setuid or setgid bit set. Please contact the security team
to have it allowed.
"""


permissions-world-writable="""
The file or directory is world-writable. Please contact the security team to
have that allowed.
"""


permissions-fscaps="""
Packaging file capabilities is currently not supported. Please use normal
permissions instead. You may contact the security team to request an entry that
sets capabilities in /usr/share/permissions/permissions instead.
"""


permissions-missing-postin="""
Please call the %set_permissions macro for this file in the %post section.
"""


permissions-missing-requires="""
Please add 'Requires: /usr/bin/chkstat' and 'Requires(post): /usr/bin/chkstat'
"""


permissions-missing-verifyscript="""
Please add call the %verify_permissions macro for this file in the
%verifyscript section.
"""


permissions-ghostfile="""
This package installs a permissions file as a %ghost file. This is not allowed
as it is impossible to review.
"""
